<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Supprime la table `stat` avec le contexte borné Portfolio\Stats.
 *
 * Le bloc de chiffres clés de l'accueil (« +50K lignes de code », « 100 %
 * engagement qualité », « ∞ Passion ») a été retiré : métriques de vanité sur
 * une page qui parle par ailleurs de revue de code et d'analyse statique. Une
 * fois le bloc parti, tout le reste de la tranche — entité, API publique, CRUD
 * backoffice, commande de seed — n'alimentait plus rien. Le conserver aurait
 * laissé un écran d'administration permettant d'éditer un contenu invisible,
 * et du code mort dans un dépôt qui sert de démonstration.
 *
 * `down()` recrée la structure, pas les données : le contenu était produit par
 * `app:stats:seed`, supprimée en même temps. C'est assumé — restaurer la table
 * sert à faire repasser les migrations, pas à ressusciter la fonctionnalité,
 * qui se retrouve dans l'historique git.
 */
final class Version20260906190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Supprime la table stat (contexte Portfolio\Stats retiré).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS stat');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE stat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(2) NOT NULL, value VARCHAR(30) NOT NULL, label VARCHAR(180) NOT NULL, icon_key VARCHAR(60) NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
    }
}
