<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Crée la table de référence du classement des technologies affiché sur la
 * page Expériences (App\Portfolio\Experience). Table vide à l'issue de cette
 * migration : le peuplement se fait exclusivement via la commande
 * app:experience:add-technology (aucun endpoint d'écriture exposé).
 */
final class Version20260809204541 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la table experience_technology (classement des technologies de la page Expériences).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE experience_technology (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, years DOUBLE PRECISION NOT NULL, icon_key VARCHAR(60) DEFAULT NULL, related_technology_name VARCHAR(180) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_experience_technology_name ON experience_technology (name)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE experience_technology');
    }
}
