<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Crée les tables quality_principle et quality_trait (principes et traits de
 * qualité de la landing page, gérés depuis le backoffice
 * App\Portfolio\Quality). Tables vides à l'issue de cette migration : le
 * peuplement du contenu FR/EN actuel se fait via la commande
 * app:quality:seed (à venir), jamais dans la migration elle-même.
 */
final class Version20260814051527 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée les tables quality_principle et quality_trait (principes et traits de qualité de la landing page, gérés depuis le backoffice).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE quality_principle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(2) NOT NULL, title VARCHAR(180) NOT NULL, description VARCHAR(500) NOT NULL, icon_key VARCHAR(60) NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE quality_trait (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(2) NOT NULL, label VARCHAR(180) NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE quality_principle');
        $this->addSql('DROP TABLE quality_trait');
    }
}
