<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Crée la table `case_study` : ADR 0003 D5, premier des trois contenus prévus
 * pour le palier de base (études de cas techniques anonymisées).
 *
 * Table vide à l'issue de cette migration — le contenu est posé par
 * `app:case-studies:seed` (à venir), jamais dans la migration elle-même :
 * c'est du contenu éditorial, il vit dans une commande rejouable et non dans
 * l'historique de schéma (même choix que Contribution/Incident).
 */
final class Version20260912174635 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la table case_study (ADR 0003 D5 : études de cas techniques du palier de base).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE case_study (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(2) NOT NULL, title VARCHAR(255) NOT NULL, problem TEXT NOT NULL, solution TEXT NOT NULL, tradeoffs TEXT NOT NULL, measured_result TEXT NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_case_study_locale_position ON case_study (locale, position)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE case_study');
    }
}
