<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Crée la table `incident` : pannes de production, cause racine et invariant
 * qui en est sorti.
 *
 * `invariant` est NOT NULL comme les autres colonnes de texte, et c'est
 * délibéré : une entrée dont on n'a tiré aucune règle n'a pas sa place sur
 * cette page. La contrainte porte la ligne éditoriale plutôt qu'une consigne
 * de rédaction.
 *
 * Table vide à l'issue de la migration — le contenu est posé par
 * `app:incidents:seed`, jamais dans la migration : c'est de l'éditorial, il
 * vit dans une commande rejouable et non dans l'historique de schéma.
 */
final class Version20260907030000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la table incident (pannes de production et invariants).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE incident (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(2) NOT NULL, title VARCHAR(255) NOT NULL, version VARCHAR(60) NOT NULL, occurred_at DATE NOT NULL, impact TEXT NOT NULL, root_cause TEXT NOT NULL, resolution TEXT NOT NULL, invariant TEXT NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_incident_locale_position ON incident (locale, position)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE incident');
    }
}
