<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Crée la table `contribution` : les contributions techniques publiques
 * affichées sur /contributions, avec le raisonnement qui les porte.
 *
 * Table vide à l'issue de cette migration — le contenu est posé par
 * `app:contributions:seed`, jamais dans la migration elle-même : c'est du
 * contenu éditorial, il vit dans une commande rejouable et non dans
 * l'historique de schéma.
 */
final class Version20260906200000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la table contribution (contributions techniques publiques).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE contribution (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(2) NOT NULL, title VARCHAR(255) NOT NULL, project VARCHAR(120) NOT NULL, reference VARCHAR(60) NOT NULL, url VARCHAR(500) NOT NULL, summary TEXT NOT NULL, body TEXT NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_contribution_locale_position ON contribution (locale, position)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE contribution');
    }
}
