<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Crée la table password_setup_token : jetons à usage unique et à durée de vie
 * limitée pour la définition de mot de passe par une personne invitée depuis
 * le backoffice. Seul le SHA-256 du jeton est stocké (token_hash, unique). La
 * FK vers cpg_user est ON DELETE CASCADE : supprimer un compte purge ses jetons.
 */
final class Version20260903160900 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la table password_setup_token (jetons de définition de mot de passe).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE password_setup_token (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, token_hash VARCHAR(64) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_46600387A76ED395 ON password_setup_token (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_password_setup_token_hash ON password_setup_token (token_hash)');
        $this->addSql('ALTER TABLE password_setup_token ADD CONSTRAINT FK_46600387A76ED395 FOREIGN KEY (user_id) REFERENCES cpg_user (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE password_setup_token DROP CONSTRAINT FK_46600387A76ED395');
        $this->addSql('DROP TABLE password_setup_token');
    }
}
