<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Crée la table stat (statistiques affichées sur la landing page, éditables
 * depuis le backoffice App\Portfolio\Stats). Table vide à l'issue de cette
 * migration : le peuplement du contenu FR/EN actuel se fait via la commande
 * app:stats:seed (à venir), jamais dans la migration elle-même.
 */
final class Version20260814050635 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la table stat (statistiques de la landing page, gérées depuis le backoffice).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE stat (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(2) NOT NULL, value VARCHAR(30) NOT NULL, label VARCHAR(180) NOT NULL, icon_key VARCHAR(60) NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE stat');
    }
}
