<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Crée la table `anonymous_cv_section` : ADR 0003 D5, deuxième des trois
 * contenus prévus pour le palier de base (le « CV sans identité »).
 *
 * Table vide à l'issue de cette migration — le contenu est posé par
 * `app:anonymous-cv:seed`, jamais dans la migration elle-même : c'est du
 * contenu éditorial, il vit dans une commande rejouable et non dans
 * l'historique de schéma (même choix que CaseStudy).
 */
final class Version20260913103000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée la table anonymous_cv_section (ADR 0003 D5 : CV sans identité du palier de base).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE anonymous_cv_section (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(2) NOT NULL, title VARCHAR(255) NOT NULL, skills TEXT NOT NULL, years_of_experience INT NOT NULL, achievements TEXT NOT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_anonymous_cv_section_locale_position ON anonymous_cv_section (locale, position)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE anonymous_cv_section');
    }
}
