<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Crée les deux tables du contexte `Portfolio/Watch` : les produits dont on
 * suit le cycle de vie, et l'instantané du dernier rafraîchissement réussi.
 *
 * `watched_product` n'a **pas** de colonne `locale`, contrairement aux autres
 * contenus de `Portfolio/*` : une version installée est un fait, pas une
 * traduction (décision D6 de la spécification).
 *
 * `watch_snapshot.type` est unique : il n'existe qu'un seul snapshot courant
 * par nature de donnée. C'est un état, pas un journal — l'historisation est
 * explicitement hors périmètre. Son `payload` est un JSON parce qu'il est écrit
 * et relu d'un bloc, jamais requêté champ par champ.
 *
 * Tables vides à l'issue de la migration : les produits suivis seront posés par
 * `app:watch:seed`, et le snapshot par `app:watch:refresh`.
 */
final class Version20260907100054 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée les tables watched_product et watch_snapshot (contexte Portfolio/Watch).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE watch_snapshot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(30) NOT NULL, payload JSON NOT NULL, refreshed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, source_status VARCHAR(10) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_watch_snapshot_type ON watch_snapshot (type)');
        $this->addSql('CREATE TABLE watched_product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slug VARCHAR(60) NOT NULL, label VARCHAR(100) NOT NULL, version_source VARCHAR(20) NOT NULL, version VARCHAR(30) DEFAULT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_watched_product_slug ON watched_product (slug)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE watch_snapshot');
        $this->addSql('DROP TABLE watched_product');
    }
}
