<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Crée les tables du contenu de la page À propos (App\Portfolio\About) :
 * about_settings (textes de section, singleton par locale, contrainte unique
 * sur locale), about_site_card et about_me_card (cartes éditables en CRUD
 * depuis le backoffice). Tables vides à l'issue de cette migration : le
 * peuplement initial se fait via une commande de seed dédiée (app:about:seed).
 */
final class Version20260814052607 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Crée les tables about_settings, about_site_card et about_me_card (contenu de la page À propos).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE about_me_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(2) NOT NULL, category VARCHAR(20) NOT NULL, title VARCHAR(180) NOT NULL, description VARCHAR(500) NOT NULL, icon_key VARCHAR(60) DEFAULT NULL, position INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE about_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(2) NOT NULL, site_eyebrow VARCHAR(180) NOT NULL, me_eyebrow VARCHAR(180) NOT NULL, technical_subtitle VARCHAR(180) NOT NULL, personal_subtitle VARCHAR(180) NOT NULL, hobbies_subtitle VARCHAR(180) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_about_settings_locale ON about_settings (locale)');
        $this->addSql('CREATE TABLE about_site_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, locale VARCHAR(2) NOT NULL, title VARCHAR(180) NOT NULL, description VARCHAR(500) NOT NULL, icon_key VARCHAR(60) DEFAULT NULL, position INT NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE about_me_card');
        $this->addSql('DROP TABLE about_settings');
        $this->addSql('DROP TABLE about_site_card');
    }
}
