#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Issue #231 — wizard 1/3 : préparer la boîte OVH et la zone Scaleway.
# Rien ici ne change ce que le public voit : la zone Scaleway n'est pas servie
# tant que les NS pointent chez Cloudflare (c'est le wizard 02 qui bascule).
#
# Ordre imposé par OVH (constaté sur l'espace client) : le domaine externe est
# d'abord VÉRIFIÉ par un CNAME dans le DNS public (48 h pour le faire), et ce
# n'est qu'ensuite que la page « diagnostic » livre les MX, SRV, SPF et DKIM.
# Le wizard se relance donc en deux fois : chaque écriture est idempotente et
# les valeurs saisies sont mémorisées (Entrée les conserve).
# shellcheck source=lib-231.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib-231.sh"

TOTAL_STAGES=9

banner "#231 · 1/3 Préparer OVH et la zone Scaleway"

# ── 1 ──────────────────────────────────────────────────────────────────────
stage "Pré-vol — outils et snapshots"
need_tools scw dig gh curl python3
say "Profil scw actif :"
scw config get default-project-id default-region 2>/dev/null | sed 's/^/    /'
say "Snapshot de la zone servie (Cloudflare) et de la zone Scaleway avant toute écriture."
snapshot_zones
show_zone
note "Le domaine est chez Scaleway (registrar), DNSSEC désactivé : aucun DS à retirer."
pause

# ── 2 ──────────────────────────────────────────────────────────────────────
stage "OVHcloud — boîte Zimbra Pro et compte contact@"
say "Une boîte réelle en France, à la place de la redirection Cloudflare (hors UE)."
open_url "https://www.ovh.com/manager/#/web/"
step "Commander 1 compte Zimbra Pro ; à l'étape du domaine : « Utiliser mon nom de domaine »"
step "  → $DOMAIN (JAMAIS « créer ou transférer » : le registrar reste Scaleway)."
step "Web Cloud → Zimbra → onglet Compte email → créer contact@$DOMAIN."
warn "Ne saisis jamais le mot de passe de la boîte dans ce terminal : rien ici n'en a besoin."
note "Le formulaire de contact du site n'est pas concerné : il envoie via Scaleway TEM."
pause "Boîte commandée et compte contact@ créé ?"

# ── 3 ──────────────────────────────────────────────────────────────────────
stage "OVHcloud — relever l'enregistrement de vérification du domaine"
say "Zimbra → onglet Domaine → ligne $DOMAIN → badge « CNAME ⓘ » (ou ⋮ → vérifier)."
say "La page « Vérification de votre domaine » donne un CNAME : sous-domaine → cible."
note "Copie le sous-domaine avec l'icône (l'affichage est tronqué) ; en entier ou sans le domaine, au choix."
ask OVH_VERIFY_TYPE "  type (CNAME en principe ; vide = pas de vérification demandée) :"
ask OVH_VERIFY_NAME "  sous-domaine (p. ex. ovh-zimbra-xxxxxxxx.$DOMAIN) :"
ask OVH_VERIFY_DATA "  cible (p. ex. ovh.com) :"
OVH_VERIFY_NAME=$(relative_name "$OVH_VERIFY_NAME")
[[ "$OVH_VERIFY_TYPE" == CNAME && -n "$OVH_VERIFY_DATA" ]] && OVH_VERIFY_DATA=$(fqdn_dot "$OVH_VERIFY_DATA")
for k in OVH_VERIFY_TYPE OVH_VERIFY_NAME OVH_VERIFY_DATA; do write_env "$k" "${!k}"; done
pause

# ── 4 ──────────────────────────────────────────────────────────────────────
stage "Publier la vérification des deux côtés — Cloudflare (servi) puis Scaleway"
if [[ -n "$OVH_VERIFY_TYPE" ]]; then
  say "Le robot OVH lit le DNS public, encore Cloudflare : sans l'enregistrement là-bas, pas de"
  say "validation avant la bascule. On le pose aussi chez Scaleway pour qu'il survive à la bascule."
  open_url "https://dash.cloudflare.com/?to=/:account/$DOMAIN/dns/records"
  step "Add record → $OVH_VERIFY_TYPE, nom « ${OVH_VERIFY_NAME:-@} », cible/contenu « ${OVH_VERIFY_DATA%.} »"
  [[ "$OVH_VERIFY_TYPE" == CNAME ]] && warn "Proxy status : DNS only (nuage gris), jamais « Proxied »."
  warn "Rien d'autre dans Cloudflare : ni MX ni SPF OVH, la redirection actuelle doit continuer."
  pause "Enregistrement ajouté chez Cloudflare ?"
  say "Vu par ${OLD_NS[0]} :"
  _answers "${OLD_NS[0]}" "${OVH_VERIFY_NAME:+$OVH_VERIFY_NAME.}$DOMAIN" "$OVH_VERIFY_TYPE" | sed 's/^/    /'
  printf '\n'
  ensure_record "$OVH_VERIFY_TYPE" "$OVH_VERIFY_DATA" "$OVH_VERIFY_NAME" "OVH - verification du domaine (#231)"
else
  note "Aucune vérification relevée : rien à faire ici."
fi
pause

# ── 5 ──────────────────────────────────────────────────────────────────────
stage "Attendre la validation OVH"
say "Le robot OVH passe en quelques minutes. Zimbra → Domaine : le statut de $DOMAIN doit"
say "quitter « CNAME » (validé, ou passer aux erreurs MX/SPF — normal, elles viennent après)."
note "Tu peux quitter ici (Ctrl-C) et relancer ce wizard plus tard : les étapes 1 à 4 se"
note "repassent en quelques Entrée, l'enregistrement déjà posé est reconnu, rien n'est refait."
if ! confirm "Le domaine est validé côté OVH ?"; then
  note "On s'arrête là ; relance 01-preparer.sh une fois le domaine validé."
  write_env OVH_VERIFY_PUBLISHED_AT "$(_existing OVH_VERIFY_PUBLISHED_AT || date -Is)"
  finish; exit 0
fi
write_env OVH_VERIFIED_AT "$(_existing OVH_VERIFIED_AT || date -Is)"
pause

# ── 6 ──────────────────────────────────────────────────────────────────────
stage "OVHcloud — relever MX, SRV, SPF et DKIM (page diagnostic)"
say "Zimbra → Domaine → ⋮ sur $DOMAIN → diagnostic. Copie chaque valeur telle quelle."
note "Vide = ne s'applique pas ; Entrée conserve une valeur déjà saisie. Hôtes en entier ou sans"
note "le domaine, avec ou sans point final : le wizard normalise."
printf '\n'
say "a) MX (priorité + hôte), dans l'ordre :"
for i in 1 2 3; do
  ask "OVH_MX_${i}_PRIO" "  MX $i — priorité (vide si aucun) :"
  ask "OVH_MX_${i}_HOST" "  MX $i — hôte :"
done
printf '\n'
say "b) SRV (autodiscover, imaps, submission… selon ce qu'OVH liste) :"
for i in 1 2 3 4; do
  ask "OVH_SRV_${i}_NAME"   "  SRV $i — nom (p. ex. _autodiscover._tcp ; vide si aucun) :"
  v="OVH_SRV_${i}_NAME"; [[ -n "${!v}" ]] || { for f in PRIO WEIGHT PORT TARGET; do printf -v "OVH_SRV_${i}_$f" ''; done; continue; }
  ask "OVH_SRV_${i}_PRIO"   "  SRV $i — priorité :"
  ask "OVH_SRV_${i}_WEIGHT" "  SRV $i — poids :"
  ask "OVH_SRV_${i}_PORT"   "  SRV $i — port :"
  ask "OVH_SRV_${i}_TARGET" "  SRV $i — cible :"
done
printf '\n'
say "c) SPF — l'enregistrement complet tel qu'OVH l'affiche (v=spf1 include:mx.ovh.com ~all),"
say "   ou seulement le mécanisme (include:mx.ovh.com) : le wizard en extrait ce qu'il faut."
ask OVH_SPF_INCLUDE "  SPF OVH :"
printf '\n'
say "d) DKIM — à activer côté OVH s'il y a un bouton, puis relever le ou les sélecteurs :"
for i in 1 2; do
  ask "OVH_DKIM_${i}_NAME" "  DKIM $i — nom (p. ex. selector1._domainkey ; vide si aucun) :"
  ask "OVH_DKIM_${i}_TYPE" "  DKIM $i — type (CNAME ou TXT) :"
  ask "OVH_DKIM_${i}_DATA" "  DKIM $i — valeur :"
done
# Normalisation : noms relatifs, cibles avec point final, SPF réduit à ses mécanismes
# (OVH affiche l'enregistrement complet ; le nôtre combine TEM et OVH en un seul).
OVH_SPF_INCLUDE=$(spf_mechanisms "$OVH_SPF_INCLUDE")
for i in 1 2 3; do
  v="OVH_MX_${i}_HOST"; [[ -n "${!v}" ]] && printf -v "$v" '%s' "$(fqdn_dot "${!v}")"
done
for i in 1 2 3 4; do
  v="OVH_SRV_${i}_NAME";   printf -v "$v" '%s' "$(relative_name "${!v}")"
  v="OVH_SRV_${i}_TARGET"; [[ -n "${!v}" ]] && printf -v "$v" '%s' "$(fqdn_dot "${!v}")"
done
for i in 1 2; do
  v="OVH_DKIM_${i}_NAME"; printf -v "$v" '%s' "$(relative_name "${!v}")"
  t="OVH_DKIM_${i}_TYPE"; v="OVH_DKIM_${i}_DATA"
  [[ "${!t}" == CNAME && -n "${!v}" ]] && printf -v "$v" '%s' "$(fqdn_dot "${!v}")"
done
for k in OVH_MX_1_PRIO OVH_MX_1_HOST OVH_MX_2_PRIO OVH_MX_2_HOST OVH_MX_3_PRIO OVH_MX_3_HOST \
         OVH_SRV_1_NAME OVH_SRV_1_PRIO OVH_SRV_1_WEIGHT OVH_SRV_1_PORT OVH_SRV_1_TARGET \
         OVH_SRV_2_NAME OVH_SRV_2_PRIO OVH_SRV_2_WEIGHT OVH_SRV_2_PORT OVH_SRV_2_TARGET \
         OVH_SRV_3_NAME OVH_SRV_3_PRIO OVH_SRV_3_WEIGHT OVH_SRV_3_PORT OVH_SRV_3_TARGET \
         OVH_SRV_4_NAME OVH_SRV_4_PRIO OVH_SRV_4_WEIGHT OVH_SRV_4_PORT OVH_SRV_4_TARGET \
         OVH_SPF_INCLUDE OVH_DKIM_1_NAME OVH_DKIM_1_TYPE OVH_DKIM_1_DATA \
         OVH_DKIM_2_NAME OVH_DKIM_2_TYPE OVH_DKIM_2_DATA; do
  write_env "$k" "${!k}"
done
pause

# ── 7 ──────────────────────────────────────────────────────────────────────
stage "Scaleway — couper l'autoconfiguration DNS de Transactional Email"
say "L'autoconfig TEM entretient SPF, MX (blackhole), DKIM et DMARC dans la zone. Inactive tant"
say "que les NS ne sont pas Scaleway, elle se réveillerait après la bascule et réécrirait le SPF"
say "et le MX posés pour OVH : on la coupe, définitivement."
note "DKIM et DMARC déjà posés restent en place : ce sont des enregistrements ordinaires."
if scw tem domain get "$(tem_domain id)" -o json | python3 -c 'import json,sys; sys.exit(0 if json.load(sys.stdin)["autoconfig"] else 1)'; then
  run_scw "Désactiver l'autoconfig TEM" tem domain update "$(tem_domain id)" autoconfig=false
else
  printf '  %s✓ déjà désactivée%s\n' "$GREEN" "$RESET"
fi
scw tem domain get "$(tem_domain id)" -o json | python3 -c 'import json,sys; d=json.load(sys.stdin); print("    status:", d["status"], "· autoconfig:", d["autoconfig"])'
pause

# ── 8 ──────────────────────────────────────────────────────────────────────
stage "Scaleway — écrire les enregistrements de messagerie"
say "Chaque écriture est affichée puis confirmée, et relue dans la zone. La zone n'est pas servie."
printf '\n'
for i in 1 2 3; do
  host="OVH_MX_${i}_HOST"; prio="OVH_MX_${i}_PRIO"
  [[ -n "${!host}" ]] || continue
  ensure_record MX "${!prio} ${!host}" "" "OVH Zimbra - boite contact@ (#231)" "${!prio}"
done
# Un MX se désigne par "<priorité> <hôte>." : sans la priorité, delete répond OK sans rien faire.
remove_record MX "0 blackhole.tem.scaleway.com." ""

for i in 1 2 3 4; do
  n="OVH_SRV_${i}_NAME"; p="OVH_SRV_${i}_PRIO"; w="OVH_SRV_${i}_WEIGHT"; po="OVH_SRV_${i}_PORT"; t="OVH_SRV_${i}_TARGET"
  [[ -n "${!n}" ]] || continue
  ensure_record SRV "${!p} ${!w} ${!po} ${!t}" "${!n}" "OVH Zimbra - SRV (#231)" "${!p}"
done

for i in 1 2; do
  name="OVH_DKIM_${i}_NAME"; type="OVH_DKIM_${i}_TYPE"; data="OVH_DKIM_${i}_DATA"
  [[ -n "${!name}" ]] || continue
  ensure_record "${!type}" "${!data}" "${!name}" "OVH Zimbra - DKIM (#231)"
done

NEW_SPF="v=spf1 $TEM_SPF_INCLUDE ${OVH_SPF_INCLUDE} ~all"
OLD_SPF="v=spf1 $TEM_SPF_INCLUDE -all"
say "SPF : TEM (envoi transactionnel) + OVH (boîte), en ~all le temps de la transition ;"
say "le wizard 03 passera en -all une fois la bascule vérifiée."
ensure_record TXT "$NEW_SPF" "" "SPF : Scaleway TEM + OVH (#231)"
remove_record TXT "$OLD_SPF" ""
remove_other_spf "$NEW_SPF"
write_env SPF_TRANSITION "$NEW_SPF"

show_zone
warn "Il doit rester UN seul TXT v=spf1 à l'apex et aucun MX blackhole. Sinon, corrige avant de continuer."
pause

# ── 9 ──────────────────────────────────────────────────────────────────────
stage "Comparaison des deux zones, enregistrement par enregistrement"
say "Ancien NS (${OLD_NS[0]}) contre nouveau NS (${NEW_NS[0]}). Écarts ATTENDUS :"
say "  · MX  : Cloudflare → OVH            · TXT apex : SPF Cloudflare+TEM → TEM+OVH"
say "  · CAA : 10 injectés par Cloudflare → letsencrypt.org seul (voulu, cf. issue)"
say "  · SRV et DKIM OVH absents chez Cloudflare ; la vérification doit être des deux côtés"
say "Tout autre écart (A, www, preprod, _dmarc, DKIM TEM) est une anomalie à corriger d'abord."
extra=()
[[ -n "$OVH_VERIFY_TYPE" ]] && extra+=("${OVH_VERIFY_NAME:+$OVH_VERIFY_NAME.}$DOMAIN $OVH_VERIFY_TYPE")
for i in 1 2 3 4; do v="OVH_SRV_${i}_NAME"; [[ -n "${!v}" ]] && extra+=("${!v}.$DOMAIN SRV"); done
for i in 1 2; do v="OVH_DKIM_${i}_NAME"; t="OVH_DKIM_${i}_TYPE"; [[ -n "${!v}" ]] && extra+=("${!v}.$DOMAIN ${!t}"); done
compare_zones "${extra[@]}" || note "$? écart(s) — vérifie qu'ils sont tous dans la liste attendue."
printf '\n'
say "Suite : 02-basculer.sh — jamais pendant un déploiement, et sans release prévue dans les 48 h."
note "OVH continuera d'afficher les MX/SPF en erreur jusqu'à la bascule : il lit le DNS public."
pause

finish
