#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Issue #231 — wizard 2/3 : basculer les serveurs de noms vers Scaleway.
# La seule action irréversible à court terme du chantier. Prérequis : 01-preparer.sh
# terminé, domaine vérifié côté OVH, aucun déploiement en cours ni prévu sous 48 h.
# shellcheck source=lib-231.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib-231.sh"

TOTAL_STAGES=5

banner "#231 · 2/3 Basculer les NS vers Scaleway"

# ── 1 ──────────────────────────────────────────────────────────────────────
stage "Garde-fous"
need_tools scw dig gh curl python3
[[ -f "$ENV_FILE" ]] || { warn "pas de fichier d'état : lance 01-preparer.sh d'abord"; exit 1; }
say "1. Aucun run de la pipeline en cours (les smoke tests et audit-prod résolvent www et preprod) :"
if pipeline_running; then
  warn "un run Pipeline est en cours — attends sa fin, ne bascule pas maintenant"; exit 1
else
  printf '    %s✓ aucun run en cours%s\n' "$GREEN" "$RESET"
fi
say "2. NS actuels au registre (.com) :"
printf '    %s\n' "$(registry_ns)"
say "3. La zone Scaleway telle qu'elle sera servie :"
show_zone
say "4. Snapshot de dernière minute."
snapshot_zones
printf '\n'
say "5. Comparaison finale (écarts attendus : MX, SPF, CAA, enregistrements OVH) :"
compare_zones || note "$? écart(s)"
printf '\n'
confirm "Le domaine est vérifié côté OVH, aucune release n'est prévue sous 48 h, les écarts sont ceux attendus ?" \
  || { note "arrêt sans rien changer"; exit 0; }
pause

# ── 2 ──────────────────────────────────────────────────────────────────────
stage "Bascule des serveurs de noms"
say "Le domaine est enregistré chez Scaleway : ses NS au registre suivent les NS de la zone."
say "Cible : ${NEW_NS[*]} (les serveurs par défaut de la zone)."
warn "Irréversible sur l'instant : le retour arrière est la même commande avec les NS Cloudflare,"
warn "propagée avec la même lenteur. Le TTL des NS au registre est de 2 jours."
run_scw "Basculer les NS" dns record update-nameservers "$DOMAIN" \
  ns.0.name="${NEW_NS[0]}" ns.1.name="${NEW_NS[1]}"
say "NS vus par la zone Scaleway :"
scw dns record list-nameservers "$DOMAIN" 2>/dev/null | sed 's/^/    /' || true
write_env NS_SWITCHED_AT "$(date -Is)"
pause

# ── 3 ──────────────────────────────────────────────────────────────────────
stage "Propagation"
say "Le registre .com d'abord (quelques minutes), puis les résolveurs publics (jusqu'à 48 h,"
say "en pratique bien moins : Cloudflare et Scaleway répondent tous deux pendant la transition)."
for i in $(seq 1 30); do
  reg=$(registry_ns)
  if [[ "$reg" == *"${NEW_NS[0]}"* ]]; then
    printf '    %s✓ registre .com : %s%s\n' "$GREEN" "$reg" "$RESET"; break
  fi
  printf '    … registre .com : %s (essai %s/30, nouvel essai dans 20 s)\n' "${reg:-?}" "$i"
  sleep 20
done
say "Résolveurs publics (NS, puis A de l'apex) :"
for r in 1.1.1.1 8.8.8.8 9.9.9.9; do
  printf '    %-9s NS: %s\n' "$r" "$(dig +short "@$r" "$DOMAIN" NS | sort | tr '\n' ' ')"
  printf '    %-9s A : %s\n' "$r" "$(dig +short "@$r" "$DOMAIN" A | tr '\n' ' ')"
done
note "Un résolveur qui montre encore Cloudflare n'est pas une erreur : il sert l'ancienne réponse"
note "jusqu'à expiration de son cache, et cette réponse est correcte (même IP)."
pause

# ── 4 ──────────────────────────────────────────────────────────────────────
stage "HTTPS — site, www, préprod"
say "Les A n'ont pas changé, donc rien ne doit bouger. Vérification quand même :"
http_check "https://$DOMAIN/healthz"
http_check "https://www.$DOMAIN/"
http_check "https://preprod.$DOMAIN/"
note "Attendu : 200 / 200 (ou 301 vers l'apex) / 401 (Basic Auth préprod), émetteur Let's Encrypt."
say "CAA vu par un résolveur public (doit finir par ne montrer que letsencrypt.org) :"
dig +short "@1.1.1.1" "$DOMAIN" CAA | sed 's/^/    /'
note "Le prochain renouvellement cert-manager (HTTP-01) ne dépend d'aucune API DNS : rien à faire."
pause

# ── 5 ──────────────────────────────────────────────────────────────────────
stage "Courrier — entrant puis sortant"
say "MX vus par 1.1.1.1 :"
dig +short "@1.1.1.1" "$DOMAIN" MX | sort -n | sed 's/^/    /'
printf '\n'
step "Entrant : depuis une adresse extérieure, envoie un mail à contact@$DOMAIN"
step "  et ouvre le webmail OVH : il doit arriver dans la boîte Zimbra, pas dans l'ancienne."
pause "Mail entrant reçu dans Zimbra ?"
step "Sortant : envoie un message via le formulaire de contact du site (https://$DOMAIN)."
step "  Dans Zimbra, affiche la source du message reçu et cherche « Authentication-Results » :"
step "  attendu  spf=pass   dkim=pass (d=$DOMAIN)   dmarc=pass"
note "TEM signe avec le sélecteur $(tem_domain project_id), présent dans la nouvelle zone."
pause "spf/dkim/dmarc = pass ?"
say "État du domaine côté TEM (doit rester « checked ») :"
scw tem domain get-last-status "$(tem_domain id)" 2>/dev/null | sed 's/^/    /' || true
write_env NS_SWITCH_VERIFIED_AT "$(date -Is)"
printf '\n'
say "Laisse l'ancienne zone et la redirection Cloudflare en place 3 à 4 jours, puis lance"
say "03-durcir.sh. Pas de release avant 24–48 h."
pause

finish
