#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Issue #231 — wizard 3/3 : durcir et nettoyer, une fois la bascule digérée.
# À lancer une première fois à J+3/J+4 après 02-basculer.sh (étapes 1 à 4), puis
# une seconde fois deux semaines plus tard pour DMARC p=reject (étape 5) : les
# étapes déjà faites se sautent d'un « n » — le fichier d'état garde les dates.
# shellcheck source=lib-231.sh
source "$(dirname "${BASH_SOURCE[0]}")/lib-231.sh"

TOTAL_STAGES=6
RUA="mailto:contact@$DOMAIN"

banner "#231 · 3/3 Durcir SPF/DMARC et retirer Cloudflare"

# ── 1 ──────────────────────────────────────────────────────────────────────
stage "Garde-fous"
need_tools scw dig gh curl python3 git
[[ -f "$ENV_FILE" ]] || { warn "pas de fichier d'état : lance les wizards 01 et 02 d'abord"; exit 1; }
switched=$(_existing NS_SWITCHED_AT || true)
say "Bascule des NS : ${switched:-inconnue (NS_SWITCHED_AT absent)}"
say "Délégation actuelle au registre .com : $(registry_ns)"
if [[ "$(registry_ns)" != *"${NEW_NS[0]}"* ]]; then
  warn "le registre ne délègue pas encore à Scaleway — rien à durcir aujourd'hui"; exit 1
fi
if [[ -n "$switched" ]]; then
  age_h=$(( ( $(date +%s) - $(date -d "$switched" +%s) ) / 3600 ))
  say "Ancienneté de la bascule : ${age_h} h"
  (( age_h >= 72 )) || warn "moins de 72 h : les étapes 2 à 4 sont prématurées (les caches peuvent encore servir Cloudflare)"
fi
say "Résolveurs publics — NS :"
for r in 1.1.1.1 8.8.8.8 9.9.9.9; do
  printf '    %-9s %s\n' "$r" "$(dig +short "@$r" "$DOMAIN" NS | sort | tr '\n' ' ')"
done
snapshot_zones
pause

# ── 2 ──────────────────────────────────────────────────────────────────────
stage "Cloudflare — retirer la redirection e-mail, puis la zone"
if confirm "Faire cette étape maintenant (J+3 ou plus, tous les résolveurs sur Scaleway) ?"; then
  open_url "https://dash.cloudflare.com/?to=/:account/$DOMAIN/email/routing"
  step "Email Routing → désactiver le routage, supprimer la règle contact@ et l'adresse de destination."
  pause "Redirection supprimée ?"
  open_url "https://dash.cloudflare.com/?to=/:account/$DOMAIN"
  step "Overview → en bas, « Remove Site from Cloudflare » (la zone entière)."
  note "Les 10 CAA injectés par Cloudflare disparaissent avec elle ; la zone Scaleway n'a que letsencrypt.org."
  pause "Zone supprimée ?"
  say "Les anciens NS ne doivent plus répondre pour le domaine (REFUSED ou vide) :"
  for ns in "${OLD_NS[@]}"; do
    printf '    %-24s %s\n' "$ns" "$(dig "@$ns" "$DOMAIN" A +noall +comments 2>/dev/null | grep -oE 'status: [A-Z]+' || echo 'pas de réponse')"
  done
  write_env CLOUDFLARE_REMOVED_AT "$(date -Is)"
else
  note "sautée"
fi
pause

# ── 3 ──────────────────────────────────────────────────────────────────────
stage "SPF — passer de ~all à -all"
current_spf=$(_existing SPF_TRANSITION || true)
[[ -n "$current_spf" ]] || current_spf=$(dig +short "@${NEW_NS[0]}" "$DOMAIN" TXT | tr -d '"' | grep '^v=spf1' || true)
say "SPF actuel : $current_spf"
if [[ "$current_spf" == *"~all" ]] && confirm "Passer en -all maintenant ?"; then
  hard_spf="${current_spf%\~all}-all"
  run_scw "Ajouter le SPF strict" dns record add "$DOMAIN" type=TXT data="$hard_spf" \
    comment="SPF : Scaleway TEM + OVH, -all (#231)"
  expect_record present TXT "$hard_spf"
  run_scw "Retirer le SPF de transition" dns record delete "$DOMAIN" type=TXT data="$current_spf"
  expect_record absent TXT "$current_spf"
  write_env SPF_TRANSITION "$hard_spf"
  show_zone TXT
  warn "Un seul TXT v=spf1 à l'apex, sinon le SPF est invalide (permerror) — corrige avant de continuer."
else
  note "inchangé"
fi
pause

# ── 4 ──────────────────────────────────────────────────────────────────────
stage "DMARC — p=quarantine avec rapports agrégés sur le domaine"
current_dmarc=$(dig +short "@${NEW_NS[0]}" "_dmarc.$DOMAIN" TXT | tr -d '"')
say "DMARC actuel : $current_dmarc"
quarantine="v=DMARC1; p=quarantine; rua=$RUA; adkim=s; aspf=s"
say "Cible        : $quarantine"
note "rua sur contact@ : les rapports XML (quelques-uns par jour) arrivent dans la boîte OVH, en France —"
note "l'ancien rua vers une adresse Gmail nominative avait été retiré le 2026-09-22 pour cette raison."
note "adkim/aspf stricts : seul $DOMAIN exact aligne ; aucun sous-domaine n'envoie de courrier."
if [[ "$current_dmarc" == *"p=none"* ]] && confirm "Passer en quarantine maintenant ?"; then
  run_scw "Remplacer _dmarc" dns record set "$DOMAIN" type=TXT name=_dmarc values.0="$quarantine" \
    comment="DMARC quarantine, rapports sur contact@ (#231, T4.3)"
  expect_record present TXT "$quarantine" _dmarc
  expect_record absent TXT "$current_dmarc" _dmarc
  write_env DMARC_QUARANTINE_AT "$(date -Is)"
  dig +short "@${NEW_NS[0]}" "_dmarc.$DOMAIN" TXT | sed 's/^/    /'
else
  note "inchangé"
fi
pause

# ── 5 ──────────────────────────────────────────────────────────────────────
stage "DMARC — p=reject après deux semaines de rapports propres (T4.3)"
q_at=$(_existing DMARC_QUARANTINE_AT || true)
if [[ -z "$q_at" ]]; then
  note "quarantine pas encore posé : reviens dans deux semaines. Étape sautée."
else
  q_age=$(( ( $(date +%s) - $(date -d "$q_at" +%s) ) / 86400 ))
  say "quarantine posé le $q_at (il y a ${q_age} j)."
  say "Dans les rapports reçus sur contact@ (XML, un par expéditeur et par jour), seuls Scaleway TEM"
  say "et OVH doivent apparaître comme sources alignées ; aucun échec sur du courrier légitime."
  if (( q_age >= 14 )) && confirm "Deux semaines de rapports propres — passer en p=reject ?"; then
    reject="v=DMARC1; p=reject; rua=$RUA; adkim=s; aspf=s"
    run_scw "Remplacer _dmarc" dns record set "$DOMAIN" type=TXT name=_dmarc values.0="$reject" \
      comment="DMARC reject, rapports sur contact@ (#231, T4.3)"
    expect_record present TXT "$reject" _dmarc
    write_env DMARC_REJECT_AT "$(date -Is)"
    dig +short "@${NEW_NS[0]}" "_dmarc.$DOMAIN" TXT | sed 's/^/    /'
  else
    note "inchangé (${q_age} j < 14, ou refusé)"
  fi
fi
pause

# ── 6 ──────────────────────────────────────────────────────────────────────
stage "Dépôt — la documentation peut enfin dire « aucun transfert hors UE »"
say "La branche feature/dns-mail-europe porte le registre RGPD §1/§8 et la politique FR/EN."
say "Elle ne devait être fusionnée qu'une fois la bascule effective : c'est le cas."
git -C "$HERE/../.." log --oneline develop..feature/dns-mail-europe 2>/dev/null | sed 's/^/    /' || true
step "Depuis la racine du dépôt : git switch feature/dns-mail-europe && git rebase develop"
step "  puis gates habituels et PR vers develop (tasks/ s'archive dans .claude/specs/archive/ au merge)."
step "Fermer l'issue #231 avec les dates de ce fichier d'état : $ENV_FILE"
note "Suivi possible, hors périmètre : activer DNSSEC (scw domain domain enable-dnssec)."
pause

finish
